name: MANUEL ULLOA
favicon: null
layout_spectrum: 0.5389786011073738
typography_spectrum: 0.7944770890753716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3929866631515324
  lightness: 0.05102340970188379
  saturation: 0.2177132461220026
  rhythmicContrast: 0.27296138228848577
purpose: []
